name: CI-CD
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover tests
      - name: Build Docker Image
        run: docker build -t devops-app:latest .
      - name: Deploy container
        run: |
          docker stop devops-container || true
          docker rm devops-container || true
          docker run -d -p 5000:5000 --name devops-container devops-app:latest
      - name: Test container HTTP
        run: |
          echo "Attente 5s pour le démarrage du container..."
          sleep 5
          curl -s http://localhost:5000
